/**
 * Extended export utilities for Traek conversations.
 *
 * Covers: print/PDF layout, Slack Block Kit, Discord embeds, and a
 * helper for programmatic print windows.
 */

import type { ConversationSnapshot, SerializedNode } from '../persistence/schemas';

// ---------------------------------------------------------------------------
// Internal helpers (shared with exportUtils.ts logic)
// ---------------------------------------------------------------------------

function buildNodeMap(nodes: SerializedNode[]): Map<string, SerializedNode> {
	const map = new Map<string, SerializedNode>();
	for (const node of nodes) map.set(node.id, node);
	return map;
}

function extractThreads(
	roots: SerializedNode[],
	nodeMap: Map<string, SerializedNode>
): SerializedNode[][] {
	const threads: SerializedNode[][] = [];

	function dfs(node: SerializedNode, path: SerializedNode[]): void {
		const newPath = [...path, node];
		const children = Array.from(nodeMap.values()).filter((n) => n.parentIds.includes(node.id));
		if (children.length === 0) {
			threads.push(newPath);
		} else {
			for (const child of children) dfs(child, newPath);
		}
	}

	for (const root of roots) dfs(root, []);
	return threads;
}

function getRoots(snapshot: ConversationSnapshot): SerializedNode[] {
	return snapshot.nodes.filter((n) => n.parentIds.length === 0);
}

function roleLabel(role: string): string {
	if (role === 'user') return 'User';
	if (role === 'assistant') return 'Assistant';
	return 'System';
}

// ---------------------------------------------------------------------------
// PDF export: HTML string with page-break hints
// ---------------------------------------------------------------------------

/**
 * Generate a self-contained HTML document optimized for PDF export.
 * Inserts page-break hints at branch points (where the tree diverges).
 *
 * The returned string can be opened in a browser and printed to PDF.
 */
export function snapshotToPDFHtml(snapshot: ConversationSnapshot): string {
	const title = snapshot.title ?? 'Untitled Conversation';
	const createdAt = new Date(snapshot.createdAt).toLocaleString();
	const nodeMap = buildNodeMap(snapshot.nodes);
	const roots = getRoots(snapshot);
	const threads = extractThreads(roots, nodeMap);

	const threadHtml = threads
		.map((thread, idx) => {
			const isBranchPoint = idx > 0;
			const branchStyle = isBranchPoint ? 'page-break-before: always;' : '';
			const messages = thread
				.map((node) => {
					const label = roleLabel(node.role);
					const cls = `role-${node.role}`;
					const content = node.content.trim() || '(No content)';
					return `
				<div class="message ${cls}">
					<div class="role-label">${label}</div>
					<div class="content">${escapeHtml(content)}</div>
				</div>`;
				})
				.join('\n');

			return `
		<div class="thread" style="${branchStyle}">
			<div class="thread-label">Branch ${idx + 1}</div>
			${messages}
		</div>`;
		})
		.join('\n<hr class="branch-divider" />\n');

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${escapeHtml(title)}</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
	font-size: 13px;
	line-height: 1.7;
	color: #111;
	background: #fff;
	padding: 32px;
	max-width: 720px;
	margin: 0 auto;
}
h1 { font-size: 22px; font-weight: 700; margin-bottom: 6px; }
.meta { font-size: 11px; color: #777; margin-bottom: 32px; }
.thread { margin-bottom: 40px; }
.thread-label {
	font-size: 10px;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.1em;
	color: #aaa;
	margin-bottom: 14px;
}
.message {
	border-left: 3px solid #e0e0e0;
	padding: 10px 14px;
	margin-bottom: 14px;
	page-break-inside: avoid;
	break-inside: avoid;
}
.message.role-user { border-left-color: #0077cc; }
.message.role-assistant { border-left-color: #c04000; }
.role-label {
	font-size: 10px;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.05em;
	margin-bottom: 6px;
	color: #888;
}
.message.role-user .role-label { color: #0077cc; }
.message.role-assistant .role-label { color: #c04000; }
.content { white-space: pre-wrap; font-size: 13px; }
.branch-divider {
	border: none;
	border-top: 1px dashed #ddd;
	margin: 28px 0;
}
footer {
	margin-top: 48px;
	border-top: 1px solid #eee;
	padding-top: 14px;
	font-size: 10px;
	color: #bbb;
	text-align: center;
}
@page { margin: 18mm 22mm; }
@media print {
	.thread[style*="page-break-before"] { page-break-before: always; }
}
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
<div class="meta">Exported from Traek · ${escapeHtml(createdAt)} · ${snapshot.nodes.length} messages</div>
${threadHtml}
<footer>Generated by Traek · traek.dev</footer>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Print window helper
// ---------------------------------------------------------------------------

/**
 * Open a print-optimised popup window for the given snapshot and trigger
 * the browser's native print dialog. Works in browser environments only.
 */
export function printConversation(snapshot: ConversationSnapshot): void {
	if (typeof window === 'undefined') return;

	const html = snapshotToPDFHtml(snapshot);
	const win = window.open('', '_blank', 'width=800,height=900');
	if (!win) return;

	win.document.open();
	win.document.write(html);
	win.document.close();

	win.addEventListener('load', () => {
		win.print();
	});
}

// ---------------------------------------------------------------------------
// Slack Block Kit
// ---------------------------------------------------------------------------

type SlackBlock =
	| { type: 'header'; text: { type: 'plain_text'; text: string } }
	| { type: 'section'; text: { type: 'mrkdwn'; text: string } }
	| { type: 'divider' }
	| { type: 'context'; elements: { type: 'mrkdwn'; text: string }[] };

/**
 * Generate a Slack Block Kit payload for sharing a Traek conversation.
 * Returns a JSON object you can POST to Slack's `chat.postMessage` API.
 */
export function snapshotToSlack(
	snapshot: ConversationSnapshot,
	options: { shareUrl?: string; maxMessages?: number } = {}
): { blocks: SlackBlock[] } {
	const { shareUrl, maxMessages = 6 } = options;
	const title = snapshot.title ?? 'Untitled Conversation';
	const nodeMap = buildNodeMap(snapshot.nodes);
	const roots = getRoots(snapshot);
	const threads = extractThreads(roots, nodeMap);

	// Pick the first (main) thread for the preview
	const mainThread = threads[0] ?? [];
	const preview = mainThread.slice(0, maxMessages);

	const blocks: SlackBlock[] = [
		{
			type: 'header',
			text: { type: 'plain_text', text: `💬 ${title}` }
		},
		{
			type: 'context',
			elements: [
				{
					type: 'mrkdwn',
					text: `*Traek Conversation* · ${snapshot.nodes.length} messages · ${threads.length} branch${threads.length !== 1 ? 'es' : ''}`
				}
			]
		},
		{ type: 'divider' }
	];

	for (const node of preview) {
		const emoji = node.role === 'user' ? '👤' : node.role === 'assistant' ? '🤖' : '⚙️';
		const label = roleLabel(node.role);
		const snippet = node.content.trim().slice(0, 280);
		const truncated = node.content.trim().length > 280 ? '…' : '';

		blocks.push({
			type: 'section',
			text: {
				type: 'mrkdwn',
				text: `${emoji} *${label}*\n>${snippet}${truncated}`
			}
		});
	}

	if (mainThread.length > maxMessages) {
		blocks.push({
			type: 'context',
			elements: [
				{
					type: 'mrkdwn',
					text: `_…and ${mainThread.length - maxMessages} more messages_`
				}
			]
		});
	}

	if (shareUrl) {
		blocks.push({ type: 'divider' });
		blocks.push({
			type: 'section',
			text: {
				type: 'mrkdwn',
				text: `<${shareUrl}|Open in Traek →>`
			}
		});
	}

	return { blocks };
}

/**
 * Serialize a Slack Block Kit payload to a JSON string.
 */
export function snapshotToSlackJSON(
	snapshot: ConversationSnapshot,
	options?: { shareUrl?: string; maxMessages?: number }
): string {
	return JSON.stringify(snapshotToSlack(snapshot, options), null, 2);
}

// ---------------------------------------------------------------------------
// Discord embed format
// ---------------------------------------------------------------------------

interface DiscordEmbed {
	title: string;
	description: string;
	color: number;
	fields: { name: string; value: string; inline?: boolean }[];
	footer: { text: string };
	url?: string;
}

interface DiscordPayload {
	content: string;
	embeds: DiscordEmbed[];
}

/**
 * Generate a Discord webhook payload for sharing a Traek conversation.
 * Returns a JSON object you can POST to a Discord webhook URL.
 */
export function snapshotToDiscord(
	snapshot: ConversationSnapshot,
	options: { shareUrl?: string; maxMessages?: number } = {}
): DiscordPayload {
	const { shareUrl, maxMessages = 4 } = options;
	const title = snapshot.title ?? 'Untitled Conversation';
	const nodeMap = buildNodeMap(snapshot.nodes);
	const roots = getRoots(snapshot);
	const threads = extractThreads(roots, nodeMap);
	const mainThread = threads[0] ?? [];
	const preview = mainThread.slice(0, maxMessages);

	const fields: { name: string; value: string; inline?: boolean }[] = preview.map((node) => {
		const label = roleLabel(node.role);
		const snippet = node.content.trim().slice(0, 200);
		const truncated = node.content.trim().length > 200 ? '…' : '';
		return {
			name: label,
			value: snippet + truncated || '*(empty)*'
		};
	});

	if (mainThread.length > maxMessages) {
		fields.push({
			name: '…',
			value: `*${mainThread.length - maxMessages} more messages*`,
			inline: true
		});
	}

	const embed: DiscordEmbed = {
		title: `💬 ${title}`,
		description: `**${snapshot.nodes.length}** messages across **${threads.length}** branch${threads.length !== 1 ? 'es' : ''}`,
		color: 0x00d8ff, // Traek cyan
		fields,
		footer: { text: 'Traek · Spatial AI Conversations · traek.dev' },
		...(shareUrl ? { url: shareUrl } : {})
	};

	return {
		content: '',
		embeds: [embed]
	};
}

/**
 * Serialize a Discord payload to a JSON string.
 */
export function snapshotToDiscordJSON(
	snapshot: ConversationSnapshot,
	options?: { shareUrl?: string; maxMessages?: number }
): string {
	return JSON.stringify(snapshotToDiscord(snapshot, options), null, 2);
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function escapeHtml(str: string): string {
	return str
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;');
}

/**
 * Count the number of branch points in a conversation tree.
 * A branch point is any node that has more than one child.
 */
export function countBranchPoints(snapshot: ConversationSnapshot): number {
	const childCounts = new Map<string, number>();

	for (const node of snapshot.nodes) {
		for (const parentId of node.parentIds) {
			childCounts.set(parentId, (childCounts.get(parentId) ?? 0) + 1);
		}
	}

	let count = 0;
	for (const c of childCounts.values()) {
		if (c > 1) count++;
	}
	return count;
}

/**
 * Get a short preview text from the first N messages of a conversation.
 */
export function getConversationPreview(snapshot: ConversationSnapshot, maxChars = 200): string {
	const mainThread = snapshot.nodes.filter((n) => n.parentIds.length === 0);
	if (mainThread.length === 0) return '';

	const firstNode = mainThread[0];
	return firstNode.content.trim().slice(0, maxChars);
}
