import type { ConversationSnapshot } from '@traek/core';
import type { FlowMetrics } from '../flow/types.js';
import type { HeatmapData } from '../heatmap/types.js';
import type { EngagementMetrics } from '../engagement/types.js';
import { analyzeFlow } from '../flow/FlowAnalyzer.js';
import { buildHeatmap } from '../heatmap/HeatmapBuilder.js';
import { analyzeEngagement } from '../engagement/EngagementMetrics.js';

export interface AnalyticsReport {
	generatedAt: string;
	snapshotTitle: string;
	flow: FlowMetrics;
	heatmap: HeatmapData;
	engagement: EngagementMetrics;
}

/**
 * Generate a full analytics report for a conversation snapshot.
 */
export function generateReport(snapshot: ConversationSnapshot): AnalyticsReport {
	return {
		generatedAt: new Date().toISOString(),
		snapshotTitle: snapshot.title ?? 'Untitled',
		flow: analyzeFlow(snapshot),
		heatmap: buildHeatmap(snapshot),
		engagement: analyzeEngagement(snapshot)
	};
}

/**
 * Serialize the report as pretty-printed JSON.
 */
export function reportToJson(report: AnalyticsReport): string {
	return JSON.stringify(report, null, 2);
}

/**
 * Serialize the report as a Markdown document.
 */
export function reportToMarkdown(report: AnalyticsReport): string {
	const { flow: f, engagement: e } = report;
	const fmt = (n: number | null, unit = '') =>
		n === null ? 'n/a' : `${Math.round(n * 100) / 100}${unit}`;
	const pct = (n: number) => `${Math.round(n * 100)}%`;

	return `# Analytics Report: ${report.snapshotTitle}

_Generated: ${report.generatedAt}_

---

## Conversation Flow

| Metric | Value |
|--------|-------|
| Total nodes | ${f.nodeCount} |
| Branches (paths) | ${f.branchCount} |
| Max depth | ${f.maxDepth} |
| Avg depth | ${fmt(f.avgDepth)} |
| Branching nodes | ${f.branchingNodeCount} |
| Avg branching factor | ${fmt(f.avgBranchingFactor)} |
| Avg response time | ${fmt(f.avgResponseTimeMs, ' ms')} |
| Median response time | ${fmt(f.medianResponseTimeMs, ' ms')} |

### Node Count by Role

| Role | Count |
|------|-------|
| User | ${f.countByRole.user} |
| Assistant | ${f.countByRole.assistant} |
| System | ${f.countByRole.system} |

### Branches

${
	f.branches.length === 0
		? '_No branches found._'
		: f.branches
				.map(
					(b) =>
						`- **Branch ${b.index + 1}**: ${b.length} nodes (${b.userTurns}u / ${b.assistantTurns}a)` +
						(b.durationMs !== null ? ` · ${Math.round(b.durationMs / 1000)}s` : '')
				)
				.join('\n')
}

---

## Engagement

| Metric | Value |
|--------|-------|
| Engagement score | **${e.score}/100** |
| Response elaboration ratio | ${fmt(e.responseElaborationRatio)} |
| Branching rate | ${pct(e.branchingRate)} |
| Exploration diversity | ${fmt(e.explorationDiversity)} |
| Conversation velocity | ${e.nodesPerMinute !== null ? `${fmt(e.nodesPerMinute)} nodes/min` : 'n/a'} |
| Deep answer rate | ${pct(e.deepAnswerRate)} |
| Code nodes | ${e.codeNodeCount} |
| Unique tags | ${e.uniqueTags.length > 0 ? e.uniqueTags.join(', ') : '_none_'} |

### Content Length by Role

| Role | Avg | Median | Max |
|------|-----|--------|-----|
| User | ${fmt(e.contentByRole.user.avgLength)} chars | ${fmt(e.contentByRole.user.medianLength)} chars | ${e.contentByRole.user.maxLength} chars |
| Assistant | ${fmt(e.contentByRole.assistant.avgLength)} chars | ${fmt(e.contentByRole.assistant.medianLength)} chars | ${e.contentByRole.assistant.maxLength} chars |
| System | ${fmt(e.contentByRole.system.avgLength)} chars | ${fmt(e.contentByRole.system.medianLength)} chars | ${e.contentByRole.system.maxLength} chars |

---

## Heatmap Summary

${
	report.heatmap.hottestNodeId
		? `- **Hottest node**: \`${report.heatmap.hottestNodeId}\` (most branches pass through)`
		: ''
}
${report.heatmap.hottestBranchIndex !== null ? `- **Most explored branch**: Branch ${report.heatmap.hottestBranchIndex + 1}` : ''}
${report.heatmap.coldestLeafId ? `- **Least explored leaf**: \`${report.heatmap.coldestLeafId}\`` : ''}

### Top 5 hottest nodes

| Node | Intensity | Branch coverage |
|------|-----------|-----------------|
${report.heatmap.nodes
	.slice(0, 5)
	.map(
		(n) =>
			`| \`${n.nodeId.slice(0, 8)}…\` | ${pct(n.intensity)} | ${n.branchCoverage} branch${n.branchCoverage !== 1 ? 'es' : ''} |`
	)
	.join('\n')}

---

_Report generated by @traek/analytics_
`;
}

/**
 * Serialize key flow + engagement metrics as CSV (for spreadsheet import).
 */
export function reportToCsv(report: AnalyticsReport): string {
	const { flow: f, engagement: e } = report;
	const rows: string[][] = [
		['metric', 'value'],
		['title', report.snapshotTitle],
		['generated_at', report.generatedAt],
		['node_count', String(f.nodeCount)],
		['branch_count', String(f.branchCount)],
		['max_depth', String(f.maxDepth)],
		['avg_depth', String(f.avgDepth)],
		['branching_node_count', String(f.branchingNodeCount)],
		['avg_branching_factor', String(f.avgBranchingFactor)],
		['avg_response_time_ms', f.avgResponseTimeMs !== null ? String(f.avgResponseTimeMs) : ''],
		[
			'median_response_time_ms',
			f.medianResponseTimeMs !== null ? String(f.medianResponseTimeMs) : ''
		],
		['user_nodes', String(f.countByRole.user)],
		['assistant_nodes', String(f.countByRole.assistant)],
		['system_nodes', String(f.countByRole.system)],
		['engagement_score', String(e.score)],
		['response_elaboration_ratio', String(e.responseElaborationRatio)],
		['branching_rate', String(e.branchingRate)],
		['exploration_diversity', String(e.explorationDiversity)],
		['nodes_per_minute', e.nodesPerMinute !== null ? String(e.nodesPerMinute) : ''],
		['deep_answer_rate', String(e.deepAnswerRate)],
		['code_node_count', String(e.codeNodeCount)],
		['unique_tag_count', String(e.uniqueTags.length)]
	];

	return rows.map((r) => r.map(csvCell).join(',')).join('\n');
}

function csvCell(v: string): string {
	if (v.includes(',') || v.includes('"') || v.includes('\n')) {
		return `"${v.replace(/"/g, '""')}"`;
	}
	return v;
}
